#pragma once

#include "NativeGameplayTags.h"

namespace CombatTags
{
    TEAMPOTATO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
    TEAMPOTATO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Healing);
    TEAMPOTATO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_MaxHealth);
    TEAMPOTATO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invincible);
    TEAMPOTATO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
}
